name: Issue Assigned Comment

on:
  issues:
    types: [assigned]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on the assigned issue
      uses: actions/github-script@v6
      with:
        script: |
          const issue_number = context.issue.number;
          const issue_assignee = context.payload.assignee.login;
          const contributing_guidelines_url = 'https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md';
          
          github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: issue_number,
            body: `Hi @${issue_assignee}, thank you for taking on this issue! Please refer to our [contributing guidelines](${contributing_guidelines_url}) for more information on how to get started.`
          });
