name: 'PR Title Checker'
on:
  pull_request_target:
    types:
      - opened
      - edited

permissions:
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Run PR Title Checker
        id: title-check
        uses: thehanimo/pr-title-checker@v1.4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-title-checker-config.json

      - name: PR title satisfied
        if: success()
        run: |
          gh issue comment ${{ github.event.pull_request.number }} -R ${{ github.repository }} --body "Hey @${{ github.actor }}! Thank you for going through the contributing guidelines. Give Krishna sometime, I hope he'll show up 😜"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Close PR if title is invalid
        if: failure()
        run: |
          gh issue comment ${{ github.event.pull_request.number }} -R ${{ github.repository }} --body $'Hey @${{ github.actor }}! Hold your horses 🐴! Thanks for your PR, but we have some style rules around here. Your PR title doesn\'t quite cut the mustard.\n\nMake sure you follow our contribution guidelines: PR titles should look like `fix-#124: Added responsiveness to the Home page screen`.\n\nCheck out our [contributor guidelines](https://github.com/krishnaacharyaa/wanderlust/blob/main/.github/CONTRIBUTING.md) for more details. Fix it up, and I'll be happy to take another look 😉.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
